name: "Namecheap Dynamic DNS"
description: "Namecheap Dynamic DNS add-on!"
version: "1.0.0"
slug: "namecheap_dynamic_dns"
init: false
arch:
  - aarch64
  - amd64
  - armv7
options:
  host: null
  domain: null
  password: null
schema:
  host: str
  domain: str
  password: password
image: edoren/hassio-{arch}-addon-namecheap-ddns
