name: "GeyserMC"
description: "GeyserMC add-on!"
version: "0.0.3"
slug: "geysermc"
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  19132/udp: 19132
ports_description:
  19132/udp: "GeyserMC access port"
# options:
#   COUCHDB_USER: null
#   COUCHDB_PASSWORD: null
# schema:
#   COUCHDB_USER: str
#   COUCHDB_PASSWORD: password
