name: "GeyserMC"
description: "GeyserMC add-on!"
version: "1.0.0"
slug: "geysermc"
init: false
arch:
  - aarch64
  - amd64
ports:
  19132/udp: 19132
ports_description:
  19132/udp: "GeyserMC access port"
options:
  version: latest
  min_memory: 512M
  max_memory: 1G
schema:
  version: str
  min_memory: str
  max_memory: str
image: edoren/hassio-{arch}-addon-geyser-mc
