name: "Porkbun Dynamic DNS"
description: "Porkbun Dynamic DNS add-on!"
version: "1.0.7"
slug: "porkbun_dynamic_dns"
init: false
arch:
    - aarch64
    - amd64
options:
    api_key: null
    secret_key: null
    domain: null
    subdomains: []
    time_update: 60
schema:
    api_key: password
    secret_key: password
    domain: str
    subdomains:
        - "match(^(\\*|(?:\\w+)(?:,\\w+)*)$)"
    time_update: int(60,)
image: edoren/hassio-{arch}-addon-porkbun-ddns
