name: "Porkbun Dynamic DNS"
description: "Porkbun Dynamic DNS add-on!"
version: "0.0.3"
slug: "porkbun_dynamic_dns"
init: false
arch:
  - aarch64
  - amd64
  - armv7
options:
  api_key: null
  secret_key: null
  domain: null
  subdomains: null
schema:
  api_key: password
  secret_key: password
  domain: str
  subdomains: "match(^(\\*|(?:\\w+)(?:,\\w+)*)$)"
